### ISSUE TITLE
SyntaxError: invalid syntax: setattr(self, f'{pbname}Std', np.nan)

### ISSUE THREAD

**Issue by esoner** [LSSTDESC/plasticc-kit#1]
Hello,
I got this error:
----------------------------------------------------------------------
  File "<ipython-input-7-baa1b57791cd>", line 35
    setattr(self, f'{pbname}Std', np.nan)
                               ^
SyntaxError: invalid syntax
----------------------------------------------------------------------
How to fix it?

With best regards,
Oleh Malyi

**Comment by esoner** [comment]
It's solved!

**Comment by gnarayan** [comment]
Best kind of issue!
