### ISSUE TITLE
Remove hardcoded path from environment files

### ISSUE THREAD

**Issue by aboucaud** [LSSTDESC/plasticc-kit#3]
@gnarayan I don't know exactly to which extent it can affect the user environment but I found these two hardcoded paths referring to your personal computer in the environment files.

https://github.com/LSSTDESC/plasticc-kit/blob/a862c2d90c86eafffeabdc1a6bec207f680a537e/conda_env_py36_i686.yml#L148

https://github.com/LSSTDESC/plasticc-kit/blob/a862c2d90c86eafffeabdc1a6bec207f680a537e/conda_env_py36_osx64.yml#L144

Best is to remove them.

**Comment by gnarayan** [comment]
These make no difference to conda when creating environments from the yml file --- it ignores prefix. Folks should use the requirements.txt in general - the conda env yml files are only included if there's some need to check against the exact environment I had.

**Comment by gnarayan** [comment]
Removed together with astropy update - thanks
